In [1]:
# splitting the string

string='Hi there Sam!'
string.split()

['Hi', 'there', 'Sam!']

# NUMPY

In [2]:
import numpy as np

In [3]:
# Create an array of 10 zeros

np_array=np.zeros(10)
np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
# Create an array of 10 fives

array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [5]:
# Create an array of all the even integers from 20 to 35

array=np.arange(20,36,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

In [6]:
#  Create a 3x3 matrix with values ranging from 0 to 8

arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
# Concadenate two arrays

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

# PANDAS

In [8]:
import pandas as pd


In [9]:
# Create a dataframe with 3 rows and 2 columns

data = {'Name': ['Tom', 'nick', 'krish', 'jack'],
        'Age': [20, 21, 19, 18]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [10]:
d = pd.date_range(start='1/1/2023', end='10/2/2023', freq='MS')    
d

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01'],
              dtype='datetime64[ns]', freq='MS')

In [11]:
# Create 2D list to DataFrame

lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['Sno', 'String','Value']) 
df

Sno String  Value
0    1    aaa     22
1    2    bbb     25
2    3    ccc     24