# Basic Python

## 1. Split this string

In [3]:
s = "Hi there Sam!"

In [4]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [5]:
planet = "Earth"
diameter = 12742

In [6]:
#a="The diameter of {.1f} is {diameter} kilometers" 
#print(a)
a = "The diameter of {0} is {1} kilometers".format(planet,diameter)
print(a)

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [23]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [24]:
print(d['k1'][3]["tricky"][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
np_array=np.zeros(10)
np_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
array=np.ones(10)*5
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [12]:
array=np.arange(20,36,2)
array

array([20, 22, 24, 26, 28, 30, 32, 34])

## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [13]:
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [14]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [8]:
import pandas as pd


In [16]:
data = {'Name': ['Tom', 'Nick', 'Krish', 'Jack'],
        'Age': [20, 21, 19, 18]}
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   Nick   21
2  Krish   19
3   Jack   18

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [17]:
d = pd.date_range(start='1/1/2023', end='10/2/2023', freq='MS')    
d

DatetimeIndex(['2023-01-01', '2023-02-01', '2023-03-01', '2023-04-01',
               '2023-05-01', '2023-06-01', '2023-07-01', '2023-08-01',
               '2023-09-01', '2023-10-01'],
              dtype='datetime64[ns]', freq='MS')

## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [18]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [19]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame(lists, columns =['Sno', 'String','Value']) 
df

Sno String  Value
0    1    aaa     22
1    2    bbb     25
2    3    ccc     24